name: Deploy App

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          sed -i "s/Version: .*/Version: ${{ env.VERSION }}/" index.html

      - name: Login to Yandex Container Registry
        run: |
          echo '${{ secrets.YC_SA_KEY }}' > sa_key.json
          cat sa_key.json | docker login \
            --username json_key \
            --password-stdin \
            cr.yandex
          rm -f sa_key.json

      - name: Build and push Docker image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/test-nginx-app:${{ env.VERSION }} .
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/test-nginx-app:${{ env.VERSION }}

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify cluster access
        run: |
          kubectl get pods -n kube-system
          kubectl config current-context

      - name: Deploy to Cluster
        run: |
          kubectl set image deployment/test-nginx \
            test-nginx=cr.yandex/${{ secrets.YC_REGISTRY_ID }}/test-nginx-app:${{ env.VERSION }} \
            -n ssilchin-nginx
