name: Deploy App

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Yandex Container Registry
        run: |
          echo '${{ secrets.YC_SA_KEY }}' > sa_key.json
          cat sa_key.json | docker login \
            --username json_key \
            --password-stdin \
            cr.yandex
          rm -f sa_key.json

      - name: Build and push Docker image
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}
          echo "Building image with tag: ${{ env.VERSION }}"
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/test-nginx-app:${{VERSION}} .
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/test-nginx-app:${{VERSION}}

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Cluster
        run: |
          kubectl set image deployment/test-nginx \
            test-nginx=cr.yandex/${{ secrets.YC_REGISTRY_ID }}/test-nginx-app:${{VERSION}} \
            -n ssilchin-nginx
